### ISSUE TITLE
Fix Spellbook to display new spells added by the Middle Earth mod

### ISSUE THREAD

**Issue by wkdgit** [DakkJaniels/DevilutionX-MiddleEarthMod#24]
currently the newly created spells for Middle Earth mod do not show up in the spell book

also pulling in kphoenix's spellbook QoL updates would be nice too

**Comment by DakkJaniels** [comment]
#32 adds Thunder to spellbook. I think Escape is already in there. Etherealize won't show up since you can only get it on scrolls.
